// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaO0-5DaCwK4U9pEIp2F7E9h6PLK1r_NU',
    appId: '1:1054264689837:web:7dd99b49fab8870c503224',
    messagingSenderId: '1054264689837',
    projectId: 'fiscus-fa2ab',
    authDomain: 'fiscus-fa2ab.firebaseapp.com',
    storageBucket: 'fiscus-fa2ab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPegnFSkjByLr3Dd7ww1XGssveLeV5wMs',
    appId: '1:1054264689837:android:f6ac64bc93a8f266503224',
    messagingSenderId: '1054264689837',
    projectId: 'fiscus-fa2ab',
    storageBucket: 'fiscus-fa2ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRHW3G_1atFY-toQA3tODyrOfzTZ4xjkM',
    appId: '1:1054264689837:ios:336b2dceab0181ae503224',
    messagingSenderId: '1054264689837',
    projectId: 'fiscus-fa2ab',
    storageBucket: 'fiscus-fa2ab.firebasestorage.app',
    iosBundleId: 'com.example.fiscus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRHW3G_1atFY-toQA3tODyrOfzTZ4xjkM',
    appId: '1:1054264689837:ios:336b2dceab0181ae503224',
    messagingSenderId: '1054264689837',
    projectId: 'fiscus-fa2ab',
    storageBucket: 'fiscus-fa2ab.firebasestorage.app',
    iosBundleId: 'com.example.fiscus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaO0-5DaCwK4U9pEIp2F7E9h6PLK1r_NU',
    appId: '1:1054264689837:web:5571e664c9dc6e01503224',
    messagingSenderId: '1054264689837',
    projectId: 'fiscus-fa2ab',
    authDomain: 'fiscus-fa2ab.firebaseapp.com',
    storageBucket: 'fiscus-fa2ab.firebasestorage.app',
  );
}
